planner_server:
  ros__parameters:
    planner_plugins: ["BFS", "DFS", "IDS", "UCS", "DIJKSTRA"]

    BFS:
      plugin: "uninformed/BFS"

    DFS:
      plugin: "uninformed/DFS"

    IDS:
      plugin: "uninformed/IDS"

    UCS:
      plugin: "uninformed/UCS"

    DIJKSTRA:
      plugin: "informed/Dijkstra"